# Generated by Django 5.1.2 on 2024-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesoffer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
